# Generated by Django 3.2.6 on 2022-01-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=280)),
                ('author', models.CharField(max_length=120)),
                ('publication_date', models.DateField()),
                ('isbn', models.IntegerField(max_length=13)),
                ('pages', models.IntegerField()),
                ('language', models.CharField(max_length=120)),
            ],
        ),
    ]
